name: GardeningTweaks
version: '${project.version}'
main: org.lushplugins.gardeningtweaks.GardeningTweaks
api-version: 1.16
authors:
  - OakLoaf
description: Spruces up your gardening
softdepend:
  - packetevents
  - ProtocolLib
  - RealisticBiomes
  - GriefPrevention
  - HuskClaims
  - HuskTowns
  - Lands
